---
# yamllint disable rule:line-length
name: Build and tests

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  build-ubuntu-latest-client:
    strategy:
      fail-fast: False
      matrix:
        os:
          - name: ubuntu-latest
    runs-on: ${{ matrix.os.name }}
    name: build client on ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: sudo apt-get -y install build-essential
      - name: Create xymon user
        run: sudo useradd xymon
      - name: configure
        run: ./configure --client
      - name: build without any optional deps
        run: make
      - name: Install optionnal packages
        run: sudo apt-get -y install libssl-dev librrd-dev libc-ares-dev
      - name: build with any optional deps
        run: make
  build-ubuntu-latest-server:
    strategy:
      fail-fast: False
      matrix:
        os:
          - name: ubuntu-latest
    runs-on: ${{ matrix.os.name }}
    name: build server on ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: sudo apt-get -y install build-essential
      - name: Create xymon user
        run: sudo useradd xymon
      - name: configure
        run: ./configure --server
      - name: build without any optional deps
        run: make
      - name: Install optionnal packages
        run: sudo apt-get -y install libssl-dev librrd-dev libc-ares-dev
      - name: build with any optional deps
        run: make
  
      - name: Install optionnal packages
        run: sudo apt-get -y install libssl-dev librrd-dev libc-ares-dev
      - name: build with any optional deps
        run: make
