.TH SHOWGRAPH.CGI 1 "Version 4.3.30:  4 Sep 2019" "Xymon"
.SH NAME
showgraph.cgi \- CGI to generate Xymon trend graphs
.SH SYNOPSIS
.B "showgraph [options]"

.SH DESCRIPTION
\fBshowgraph.cgi\fR
is invoked as a CGI script via the showgraph.sh CGI wrapper.

showgraph.cgi is passed a QUERY_STRING environment variable with the
following parameters:
.sp
.IP "\fBhost\fR"
Name of the host to generate a graph for
.IP "\fBservice\fR"
Name of the service to generate a graph for
.IP "\fBdisp\fR"
Display-name of the host, used on the generated graphs instead of hostname.
.IP "\fBgraph\fR"
Can be "hourly", "daily", "weekly" or "monthly" to select the time period
that the graph covers.
.IP "\fBfirst\fR"
Used to split multi-graphs into multiple graphs. This causes showgraph.cgi
to generate only the graphs starting with the "first'th" graph and continuing
for "count".
.IP "\fBcount\fR"
Number of graphs in a multi-graph.
.IP "\fBupper\fR"
Set the upper limit of the graph. See
.I rrdgraph(1)
for a description of the "\-u" option.
.IP "\fBlower\fR"
Set the lower limit of the graph. See
.I rrdgraph(1)
for a description of the "\-l" option.
.IP "\fBgraph_start\fR"
Set the starttime of the graph. This is used in zoom-mode.
.IP "\fBgraph_end\fR"
Set the end-time of the graph. This is used in zoom-mode.
.IP "\fBaction=menu\fR"
Generate an HTML page with links to 4 graphs, representing the
hourly, weekly, monthly and yearly graphs. Doesn't actually generate
any graphs, only the HTML that links to the graphs.
.IP "\fBaction=selzoom\fR"
Generate an HTML page with link to single graph, and with JavaScript code 
that lets the user select part of the graph for a zoom-operation. The 
JavaScript invokes showgraph.cgi with "action=showzoom" to generate the
zoomed graph webpage.
.IP "\fBaction=showzoom\fR"
Generate HTML with a link to the zoomed graph image. This link goes to
an "action=view" invocation of showgraph.cgi.
.IP "\fBaction=view\fR"
Generate a single graph image.
.SH OPTIONS
.IP "\fB\-\-config=FILENAME\fR"
Loads the graph configuration file from FILENAME. If not specified,
the file $XYMONHOME/etc/graphs.cfg is used. See the
.I graphs.cfg(5)
for details about this file.

.IP "\fB\-\-env=FILENAME\fR"
Loads the environment settings defined in FILENAME before executing
the CGI.

.IP "\fB\-\-rrddir=DIRECTORY\fR"
The top-level directory for the RRD files. If not specified, the
directory given by the XYMONRRDS environment is used.

.IP "\fB\-\-save=FILENAME\fR"
Instead of returning the image via the CGI interface (i.e. on stdout),
save the generated image to FILENAME.

.IP "\fB\-\-debug\fR"
Enable debugging output.

.SH ENVIRONMENT
.sp
.IP "\fBQUERY_STRING\fR"
Provided by the webserver CGI interface, this decides what graph
to generate.
.IP "\fBRRDGRAPHOPTS\fR"
RRD-specific options for the graph. This is usually set in the
.I xymonserver.cfg(5)
file.
.SH FILES
.sp
.IP "\fBgraphs.cfg:\fR"
The configuration file determining how graphs are generated from
RRD files.
.SH "SEE ALSO"
graphs.cfg(5), xymon(7), rrdtool(1)

